### ISSUE TITLE
volume_overlay function display error color

### ISSUE THREAD

**Issue by jiapengfei** [matplotlib/mpl_finance#19]
When the open and close are same price, the color is the down color, but it should be the up color.
Current code:
`colors = [colord[open < close]`
              `for open, close in zip(opens, closes)`
              `if open != -1 and close != -1]`
I think the compare between open and close should be close >= open, see below:
`colors = [colord[close >= open]`
              `for open, close in zip(opens, closes)`
             `if open != -1 and close != -1]`

**Comment by DanielGoldfarb** [comment]
Try using function `volume_overlay3()`.  I think it does what you want.

**Comment by DanielGoldfarb** [comment]
The code is inconsistent as to how it treats open equals close:  In most places equal is given the up color.  In three places it is given the down color.  It makes sense to make the code consistent.  _Can you please post, to a github gist, your own code to form your plot with a volume overlay, so that I can be sure I can reproduce and see exactly what you are seeing?  Then please provide a link here to the gist._   (A screen shot would also be helpful).  Thank you.

**Comment by DanielGoldfarb** [comment]
@jiapengfei  not sure if you saw my previous comment.   Adding an @... style comment so that you will get an email.  Please see comment above and respond.  Thank you.

**Comment by DanielGoldfarb** [comment]
https://pypi.org/project/mplfinance/ handles volume easily
